apiVersion: apps/v1
kind: Deployment
metadata:
  name: job
spec:
  replicas: 3
  selector:
    matchLabels:
      app: job
  template:
    metadata:
      labels:
        app: job
    spec:
      containers:
      - name: job
        image: karolinpreethy/jobportal11
        imagePullPolicy: Always
        ports:
        - containerPort: 5000